server: "{{ lookup('file', 'server_info.json') }}"
fulldomain: "{{ server.info[0].fulldomainname }}"
domain: "{{ server.info[0].domainname }}"

sudo_user: "{{ lookup('file', 'sudo_users.json') }}"
wheel_user: "{{ lookup('file', 'wheel_users.json') }}"
packages: ['docker', 'mysql', 'nginx']