- name: Generate Basic Authen
  shell: "htpasswd -c -b /etc/nginx/authentication/.htpasswd.{{ item.servername }}.{{ item.fulldomainname }} {{ item.servername }} {{ item.basicauthen }}"
  loop: "{{ server.info }}"
  tags: authen

# Generate an OpenSSL private key with the values (4096 bits, RSA)
- name: Generate Website Private key
  openssl_privatekey:
    path: /etc/nginx/certs/{{ fulldomain }}/{{ domain }}.key
    size: 4096
    type: RSA
  tags: private key

# Generate an OpenSSL Certificate Signing Request
- name: Generate Certificate Signing Request
  openssl_csr:
    path: /etc/nginx/certs/{{ fulldomain }}/{{ domain }}.csr
    privatekey_path: /etc/nginx/certs/{{ fulldomain }}/{{ domain }}.key
  tags: csr

- name: Generate a Self Signed OpenSSL certificate
  openssl_certificate:
    path: /etc/nginx/certs/{{ fulldomain }}/{{ domain }}_bundle.crt
    privatekey_path: /etc/nginx/certs/{{ fulldomain }}/{{ domain }}.key
    csr_path: /etc/nginx/certs/{{ fulldomain }}/{{ domain }}.csr
    provider: selfsigned
  tags: ssl