- name: Reverse Proxy Setup
  block:
    - name: Copying configuration
      template:
        src: 'project.j2'
        dest: '/etc/nginx/conf.d/{{ item.servername }}.{{ item.domainname }}.conf'
        owner: root
        group: root
        mode: "644"
      loop: "{{ proxy_info }}"
      

    # - name: Generate Basic Authen
    #   htpasswd:
    #     path: /etc/nginx/authen/.htpasswd-{{ item.servername }}
    #     name: "{{ item.servername }}.{{ item.domainname }}"
    #     password: "{{ item.password }}"
    #     owner: root
    #     group: root
    #     mode: '640'
    #   loop: "{{ server.info }}"
    
    - name: Generate Basic Authen
      command:  "htpasswd -c -b .htpasswd-{{ item.servername }} {{ item.servername }}.{{ item.domainname }} {{ item.authen_password }}"
      args:
        chdir: /etc/nginx/authen/
      loop: "{{ proxy_info }}"
      notify: Reload Reverse-Proxy
      tags: authen
      


