- name: Ubuntu Server
  become: yes
  block:  
    - name: Installing System Packages
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop: "{{ sys_packages }}"
  when: ansible_facts['distribution'] == "Ubuntu"

- name: CentOS Server
  become: yes
  block:  
    - name: Installing System Packages
      yum:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop: "{{ packages }}"
  when: ansible_facts['distribution'] == "CentOS"