    # - name: Installation install software-properties-common
    #   apt: name=software-properties-common

    - name: "Repo PHP {{php_version}}"
      apt_repository:
        repo="ppa:ondrej/php"
   
    - name: "Updating the repo"
      apt: update_cache=yes

    - name: Installation PHP {{php_version}}
      apt: 
        name: php{{php_version}} 
        state: present

    - name: Install Packages Needed To Compile PHP 7
      apt: pkg={{ item }} state=latest
      with_items:
        - git
        - net-tools
        - autoconf 
        - bison 
        - libxml2-dev 
        - libbz2-dev 
        - libmcrypt-dev 
        - libcurl4-openssl-dev 
        - libltdl-dev 
        - libpng-dev 
        - libpspell-dev
        - libreadline6-dev