- name: A Block of tasks
  block:
    - name: RVM GPG key
      command: "gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys {{ rvm_keylist }}"

    - name: Installing RVM on User {{ item }}
      shell: "curl -sSL https://get.rvm.io | bash -s stable"

    - name: "Add RVM environment variable to user {{ item }}"
      blockinfile:
        path: "~/.bashrc"
        block: |
          if [ -f $HOME/.rvm/scripts/rvm ]; then
            source $HOME/.rvm/scripts/rvm
          fi
          rvm use {{ ruby_version }} --default

    - name: "Installing Ruby-{{ ruby_version }} on user {{ item }}"
      shell: "{{ install_process_list }}"
      environment:
        PATH: "{{ RVM_ENVIRONMENT }}:{{ ansible_env.PATH }}"

 
