---
# tasks file for roles/local-confdig

- name: Changing Hostname
  hostname: 
    name: "{{ item.hostname }}"
  loop: "{{ info.config }}"

- name: Changing /etc/hosts
  lineinfile:
    path: /etc/hosts
    regexp: '127.0.0.1 template'
    line: "127.0.0.1 {{ item.hostname }}"
    state: "present"
  loop: "{{ info.config }}"
  
# CentOS
- name: CentOS Local Config
  block:
    - name: Changing IP Address
      replace:
        path: /etc/sysconfig/network-scripts/ifcfg-eth0
        regexp: "{{ ansible_host }}" 
        replace: "{{ item.IpAdresss }}"
      loop: "{{ info.config }}"
    - name: Deleting extra ssh config line
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "PasswordAuthentication yes"
        state: "absent"
    - name: Changing ssh config
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '#PasswordAuthentication yes'
        line: "PasswordAuthentication no"
        state: "present"  
  when: ansible_facts['distribution'] == "CentOS"

# Debian
- name: Ubuntu/Debian Local Config
  block:
    - name: Changing IP Address
      lineinfile:
        path: /etc/netplan/00-installer-config.yaml
        backrefs: yes
        regexp: '^(\s*)[#]?- {{ ansible_host }}(: )*' 
        line: '\1- {{ item.IpAdresss }}/24'
        state: "present"
      loop: "{{ info.config }}"
      notify: Restart Netplan
    - name: Deleting extra ssh config line
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "PasswordAuthentication yes"
        state: "absent"
    - name: Changing ssh config
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "#PasswordAuthentication yes"
        line: "PasswordAuthentication no"
        state: "present"
  when: ansible_facts['distribution'] == "Ubuntu"