# CentOS
- name: User-Creation on CentOS
  block:
    - name: Creating User
      user:
        name: "{{ item.name }}"
        create_home: yes
        append: "{{ item.append }}"
        groups: "{{ item.group }}"
        shell: "{{ item.shell }}"
        password: "{{ item.password | password_hash('sha512') }}"
        state: present
      loop: "{{ wheel_user }}"
      
    - name: Creating User Public Key
      authorized_key:
        user: "{{ item.name }}"
        state: present
        key: "{{ item.pubkey }}"
      loop: "{{ wheel_user }}"
  when: ansible_facts['distribution'] == "CentOS"

# Debian
- name: User-Creation on Ubuntu/Debian
  block:
    - name: Creating User
      user:
        name: "{{ item.name }}"
        create_home: yes
        append: "{{ item.append }}"
        groups: "{{ item.group }}"
        shell: "{{ item.shell }}"
        password: "{{ item.password | password_hash('sha512') }}"
        state: present
      loop: "{{ sudo_user }}"

    - name: Creating User Public Key
      authorized_key:
        user: "{{ item.name }}"
        state: present
        key: "{{ item.pubkey }}"
      loop: "{{ sudo_user }}"
  when: ansible_facts['distribution'] == "Ubuntu"


